services:
    ue-aniceto-arce:
        image: app-ue-aniceto-arce:1.0.0
        container_name: app-ue-aniceto-arce
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - ".env.docker:/var/www/.env"
        ports:
            - "8000:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ue-aniceto-arce.rule=Host(`${TRAEFIK_HTTP_ROUTERS_RULE_HOST}`)"
            - "traefik.http.routers.ue-aniceto-arce.entrypoints=websecure"
            - "traefik.http.routers.ue-aniceto-arce.tls.certresolver=myresolver"
        restart: unless-stopped
        networks:
            - web

networks:
    web:
        external: true
