services:
    ue_aniceto_arce:
        image: app-ue_aniceto_arce:1.0.0
        container_name: app-ue_aniceto_arce
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - ".env.docker:/var/www/.env"
        ports:
            - "8000:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ue_aniceto_arce.rule=Host(`${TRAEFIK_HTTP_ROUTERS_RULE_HOST}`)"
            - "traefik.http.routers.ue_aniceto_arce.entrypoints=websecure"
            - "traefik.http.routers.ue_aniceto_arce.tls.certresolver=myresolver"
        networks:
            - web

networks:
    web:
        external: true
