export default {
    dark: true,
    colors: {
        background: "#121212",
        surface: "#141518",
        "surface-bright": "#FFFFFF",
        "surface-light": "#EEEEEE",
        "surface-variant": "#424242",
        "on-surface-variant": "#FFFFFF",
        primary: "#CE2D4F",
        "primary-darken-1": "#6F041A",
        secondary: "#1EFFBC",
        "secondary-darken-1": "#037661",
        error: "#FC440F",
        info: "#4056F4",
        success: "#00FDDC",
        warning: "#FF8811",
    },
    variables: {
        "border-color": "#FFFFFF",
        "border-opacity": 0.85,
        "high-emphasis-opacity": 0.87,
        "medium-emphasis-opacity": 0.6,
        "disabled-opacity": 0.38,
        "idle-opacity": 0.04,
        "hover-opacity": 0.04,
        "focus-opacity": 0.12,
        "selected-opacity": 0.08,
        "activated-opacity": 0.22,
        "pressed-opacity": 0.12,
        "dragged-opacity": 0.08,
        "theme-kbd": "#212529",
        "theme-on-kbd": "#FFFFFF",
        "theme-code": "#F5F5F5",
        "theme-on-code": "#000000",
    },
};
