export default {
    dark: false,
    colors: {
        background: "#FFFFFF",
        surface: "#FCFCFC",
        "surface-bright": "#FFFFFF",
        "surface-light": "#EEEEEE",
        "surface-variant": "#424242",
        "on-surface-variant": "#EEEEEE",
        // primary: "#19659d",
        // "primary-darken-1": "#071c2b",
        primary: "#19659d",
        "primary-darken-1": "#071c2b",
        secondary: "#ae0914",
        "secondary-darken-1": "#7b060e",
        error: "#e17635",
        info: "#553a30",
        success: "#085c39",
        warning: "#ffcf03",
    },
    variables: {
        "border-color": "#222C58",
        "border-opacity": 0.22,
        "high-emphasis-opacity": 0.87,
        "medium-emphasis-opacity": 0.6,
        "disabled-opacity": 0.38,
        "idle-opacity": 0.04,
        "hover-opacity": 0.04,
        "focus-opacity": 0.12,
        "selected-opacity": 0.08,
        "activated-opacity": 0.22,
        "pressed-opacity": 0.12,
        "dragged-opacity": 0.08,
        "theme-kbd": "#212529",
        "theme-on-kbd": "#FFFFFF",
        "theme-code": "#F5F5F5",
        "theme-on-code": "#000000",
    },
};
